name: Download with yt-dlp

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3
        # FFmpeg و aria2 به صورت خودکار تنظیم می‌شوند

      - name: Download video
        run: |
          yt-dlp -o "video.%(ext)s" "${{ github.event.inputs.url }}"

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: ./video.*
